### PR TITLE
Add readme/notice functionality

### PR DESCRIPTION
**Pull request by evwltrs**
This adds functionality to read from a `readme.txt` file and present it as a notice at the top of a directory.

Sample is attached.

Let me know if you want anything changed, or this implementation causes any issues :)
image

### CODE REVIEW

**Comment by v1rx** [comment]
Using a similar method with markdown for mine. Looks good man.

**Comment by evwltrs** [comment]
> Using a similar method with markdown for mine. Looks good man.

Thanks,
I might implement markdown as well. I have no experience with rending markdown on the web, so I will have to look into a parser that can handle this.

**Comment by evwltrs** [comment]
Now works with markdown, issue is code blocks don't render. Is this something that needs fixing?

**Comment by evwltrs** [comment]
cc @v1rx

**Comment by evwltrs** [comment]
image
Just deployed to production and it seems to be working great :)

**Comment by sixem** [comment]
I added an option to enable/disable the readme feature, as well as an option to hide the readme file. I also made some slight changes to the way the readme is being displayed (most notably a header and a container was added).

Feel free to test them, and also to let me know if you are OK with these changes 😄

**Comment by evwltrs** [comment]
Looks good 👍👌

**Pull request merged**
